services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
      - 192.168.66.3:9200:9200
      - 192.168.66.3:9300:9300
    hostname: sshks-es3
    extra_hosts:
      - sshks-es1:192.168.66.125
      - sshks-es2:192.168.66.5
    environment:
      - ELASTIC_PASSWORD=<<< password >>>
      - cluster.name=sshks
      - discovery.seed_hosts=sshks-es1,sshks-es2,sshks-es3
      - network.publish_host=192.168.66.3
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/sshks-es3/sshks-es3.key
      - xpack.security.http.ssl.certificate=certs/sshks-es3/sshks-es3.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/sshks-es3/sshks-es3.key
      - xpack.security.transport.ssl.certificate=certs/sshks-es3/sshks-es3.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
      - path.repo=/usr/share/elasticsearch/data/backup
    mem_limit: 19327352832
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  certs:
  elasticsearch-data:
